#!/bin/sh

sshpass -p astronomer ssh astronomer@192.168.0.55 "uhd_usrp_probe --args type=b200"
sshpass -p astronomer ssh astronomer@192.168.0.58 "uhd_usrp_probe --args type=b200"

sshpass -p astronomer scp *.py pobserve  ~/bin2fil-py/bin2fil.py astronomer@192.168.0.55:
sshpass -p astronomer scp *.py pobserve  ~/bin2fil-py/bin2fil.py astronomer@192.168.0.58:


if [ -e first.pid ]
then
	kill -1 `cat first.pid`
fi

if [ -e second.pid ]
then
	kill -1 `cat second.pid`
fi

startt=`date +%s`
startt=`expr $startt + 30`

sshpass -p astronomer ssh astronomer@192.168.0.55 "source .bashrc; ./pobserve --startt ${startt} --freq 611e6 --source B0329+54\
  --ra 3.51 --dec 54.5  --srate 6e6 --runtime 120 --rfgain 30 --datadir /mnt/data"  >first.log 2>&1 &

echo $! >first.pid

sshpass -p astronomer ssh astronomer@192.168.0.58 "source .bashrc; ./pobserve --startt ${startt} --freq 611e6 --source B0329+54\
  --ra 3.51 --dec 54.5  --srate 6e6 --runtime 120 --rfgain 30  --datadir /mnt/data" >second.log 2>&1 &

echo $! >second.pid

